"""r1b_tools_reservations_reviews

Revision ID: c1e5a0519059
Revises: 9f56f8f2225b
Create Date: 2026-06-23 08:43:32.916074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1e5a0519059'
down_revision: Union[str, None] = '9f56f8f2225b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', postgresql.ENUM('HAND_TOOLS', 'POWER_TOOLS', 'GARDEN_TOOLS', 'CLEANING_TOOLS', 'OUTDOOR_GEAR', name='tool_category'), nullable=False),
    sa.Column('condition', postgresql.ENUM('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'POOR', name='tool_condition'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_by', postgresql.ENUM('OWNER', 'ADMIN', name='deactivation_actor'), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_category'), 'tools', ['category'], unique=False)
    op.create_index(op.f('ix_tools_is_active'), 'tools', ['is_active'], unique=False)
    op.create_index(op.f('ix_tools_owner_id'), 'tools', ['owner_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_tool_id'), 'photos', ['tool_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('borrower_id', sa.Uuid(), nullable=False),
    sa.Column('state', postgresql.ENUM('REQUESTED', 'APPROVED', 'PICKED_UP', 'RETURNED', 'DENIED', 'CANCELLED', name='reservation_state'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('cancelled_by_type', sa.String(length=20), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('denied_reason', sa.Text(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('damage_reported', sa.Boolean(), nullable=False),
    sa.Column('damage_description', sa.Text(), nullable=True),
    sa.Column('damage_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_resolved_by', sa.Uuid(), nullable=True),
    sa.Column('force_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_resolution_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['force_resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_borrower_id', 'reservations', ['borrower_id'], unique=False)
    op.create_index('ix_reservations_date_range', 'reservations', ['tool_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_reservations_state', 'reservations', ['state'], unique=False)
    op.create_index('ix_reservations_tool_id', 'reservations', ['tool_id'], unique=False)
    op.create_index('ix_reservations_tool_state', 'reservations', ['tool_id', 'state'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewee_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'reviewer_id', name='uq_review_res_reviewer')
    )
    op.create_index(op.f('ix_reviews_reservation_id'), 'reviews', ['reservation_id'], unique=False)
    # GiST EXCLUDE constraint — prevent overlapping active reservations for the same tool
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        "ALTER TABLE reservations ADD CONSTRAINT ex_no_overlap_active "
        "EXCLUDE USING GIST ("
        "    tool_id WITH =,"
        "    tsrange(start_date, end_date, '[]') WITH &&"
        ") WHERE (state IN ('REQUESTED', 'APPROVED', 'PICKED_UP'))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reservation_id'), table_name='reviews')
    op.drop_table('reviews')
    op.execute("ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ex_no_overlap_active")
    op.drop_index('ix_reservations_tool_state', table_name='reservations')
    op.drop_index('ix_reservations_tool_id', table_name='reservations')
    op.drop_index('ix_reservations_state', table_name='reservations')
    op.drop_index('ix_reservations_date_range', table_name='reservations')
    op.drop_index('ix_reservations_borrower_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_photos_tool_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_tools_owner_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_is_active'), table_name='tools')
    op.drop_index(op.f('ix_tools_category'), table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
